#!/usr/bin/env python3

import os
import getpass
import natsort
import argparse
import awkward as ak
from config import xs_dict


parser = argparse.ArgumentParser(description="Merge parquets generated by parquet.py")
parser.add_argument("--version", type=str, required=True, help="Sample version")
parser.add_argument(
    "--year", type=str, choices=["2016APV", "2016", "2017", "2018"], required=True, help="Data taking year"
)
parser.add_argument("--mode", type=str, choices=["Wcb", "ttWcb"], required=True, help="Event selection mode")
parser.add_argument("--type", type=str, choices=["Data", "MC"], required=True, help="Event type")
options = parser.parse_args()

USER = getpass.getuser()
PREFIX = f"/data/bond/{USER}"
INDIR = f"{PREFIX}/Parquet/{options.version}/{options.year}/{options.mode}/{options.type}/"

infiles = {}
for process in natsort.natsorted(os.listdir(INDIR)):
    if not os.path.isdir(os.path.join(INDIR, process)):
        continue
    filenames = os.listdir(os.path.join(INDIR, process))
    proc_matching = None
    if options.type == "MC":
        for proc in xs_dict:
            if process.startswith(proc):
                assert not proc_matching
                proc_matching = proc
        assert proc_matching
    else:
        proc_matching = process
    for filename in natsort.natsorted(filenames):
        if filename.endswith(".parquet"):
            if proc_matching not in infiles:
                infiles[proc_matching] = []
            infiles[proc_matching].append(os.path.join(INDIR, process, filename))
for proc, proc_infiles in infiles.items():
    if not proc_infiles:
        continue
    events = []
    if options.type == "MC":
        nevent = 0.0
    for infile in proc_infiles:
        print("Read:", infile)
        events.append(ak.from_parquet(infile))
        if options.type == "MC":
            with open(infile + ".nevent") as f:
                nevent += float(f.read())
    events = ak.concatenate(events)
    if options.type == "MC":
        print(f"{proc}: {nevent} events in NanoAOD")
        events["weight"] = events["weight"] / max(nevent, 1)
    print("Write:", proc + ".parquet")
    ak.to_parquet(events, os.path.join(INDIR, proc + ".parquet"))
