#!/usr/bin/env python3

import os
from JobManager import JobManager

jsons = [
    "json/DAS_2016APVB1_JetHT.json",
    "json/DAS_2016APVB2_JetHT.json",
    "json/DAS_2016APVC_JetHT.json",
    "json/DAS_2016APVD_JetHT.json",
    "json/DAS_2016APVE_JetHT.json",
    "json/DAS_2016APVF_JetHT.json",
    "json/DAS_2016APVB1_SingleElectron.json",
    "json/DAS_2016APVB2_SingleElectron.json",
    "json/DAS_2016APVC_SingleElectron.json",
    "json/DAS_2016APVD_SingleElectron.json",
    "json/DAS_2016APVE_SingleElectron.json",
    "json/DAS_2016APVF_SingleElectron.json",
    "json/DAS_2016APVB1_SingleMuon.json",
    "json/DAS_2016APVB2_SingleMuon.json",
    "json/DAS_2016APVC_SingleMuon.json",
    "json/DAS_2016APVD_SingleMuon.json",
    "json/DAS_2016APVE_SingleMuon.json",
    "json/DAS_2016APVF_SingleMuon.json",
    "json/DAS_2016APVB1_SingleElectron.json",
    "json/DAS_2016APVB2_SingleElectron.json",
    "json/DAS_2016APVC_SingleElectron.json",
    "json/DAS_2016APVD_SingleElectron.json",
    "json/DAS_2016APVE_SingleElectron.json",
    "json/DAS_2016APVF_SingleElectron.json",
    "json/DAS_2016APVB1_SingleMuon.json",
    "json/DAS_2016APVB2_SingleMuon.json",
    "json/DAS_2016APVC_SingleMuon.json",
    "json/DAS_2016APVD_SingleMuon.json",
    "json/DAS_2016APVE_SingleMuon.json",
    "json/DAS_2016APVF_SingleMuon.json",
]
odirs = [
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/Wcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
    '/eos/user/l/legao/NtupleStore/V0/2016APV/ttWcb/Data',
]
wdirs = [
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_Wcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
    'production/2016APV_Data_ttWcb',
]

name = os.path.basename(__file__)
if name.startswith('fetch'):
    manager = JobManager(odirs, jsons)
    manager.fetch()
elif name.startswith('supply'):
    manager = JobManager(odirs, jsons, wdirs)
    manager.supply()
else:
    raise ValueError('unexpected name: ' + name)
